import {
    writable
} from 'svelte/store';


export const pages = {
    storie:"first dolor sit amet consectetur adipisicing elit. Sed velit, officiis rerum voluptas aspernatur eligendi, ipsam odit assumenda sit perspiciatis sapiente reiciendis, quis cum molestiae placeat. Quas exercitationem molestiae magnam! Lorem ipsum, dolor sit amet consectetur adipisicing elit. Perspiciatis, consequatur quos! Voluptate distinctio aspernatur iure minus explicabo sequi ipsa, iste adipisci in nihil blanditiis molestiae voluptates, amet enim, consequuntur molestias.",
    storie2:"Second funky sit amet consectetur adipisicing elit. Ea, voluptas. Accusamus unde in beatae aliquid, et dignissimos quia! Optio, et quia? Non deserunt explicabo voluptates esse sequi officiis aut laborum.  Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus consectetur cum quam nemo recusandae quidem consequuntur. Dolore eos cum nesciunt asperiores alias numquam accusantium ipsum quaerat eveniet, fugit, voluptates dolores? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Tempore quasi nihil eligendi. Magni omnis illum quae, numquam beatae sint cupiditate rerum quia eius reiciendis et ipsa repudiandae sit similique. A.",
    storie3: "Third explicabo voluptates esse sequi officiis aut laborum.  Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus consectetur cum Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ea, voluptas. Accusamus unde in beatae aliquid, et dignissimos quia! Optio, et quia? Non deserunt quam nemo recusandae quidem consequuntur. Dolore eos cum nesciunt asperiores alias numquam accusantium ipsum quaerat eveniet, fugit, voluptates dolores? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Tempore quasi nihil eligendi. Magni omnis illum quae, numquam beatae sint cupiditate rerum quia eius reiciendis et ipsa repudiandae sit similique. A.",
    storie4: " Fourth Tempore quasi nihil eligendi. Magni omnis illum quae, numquam beatae sint cupiditate rerum quia eius reiciendis et ipsa repudiandae sit similique. A.Third explicabo voluptates esse sequi officiis aut laborum.  Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus consectetur cum Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ea, voluptas. Accusamus unde in beatae aliquid, et dignissimos quia! Optio, et quia? Non deserunt quam nemo recusandae quidem consequuntur. Dolore eos cum nesciunt asperiores alias numquam accusantium ipsum quaerat eveniet, fugit, voluptates dolores? Lorem ipsum dolor sit amet consectetur, adipisicing elit. hird explicabo voluptates esse sequi officiis aut laborum.  Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus consectetur cum Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ea, voluptas. Accusamus unde in beatae aliquid, et dignissimos quia! Optio, et quia? Non deserunt quam nemo recusandae quidem consequuntur. Dolore eos cum nesciunt asperiores alias numquam accusantium ipsum quaerat eveniet, fugit, voluptates dolores? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Tempore quasi nihil eligendi. Magni omnis illum quae, numquam beatae sint cupiditate rerum quia eius reiciendis et ipsa repudiandae sit similique. A. hird explicabo voluptates esse sequi officiis aut laborum.  Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus consectetur cum Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ea, voluptas. Accusamus unde in beatae aliquid, et dignissimos quia! Optio, et quia? Non deserunt quam nemo recusandae quidem consequuntur. Dolore eos cum nesciunt asperiores alias numquam accusantium ipsum quaerat eveniet, fugit, voluptates dolores? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Tempore quasi nihil eligendi. Magni omnis illum quae, numquam beatae sint cupiditate rerum quia eius reiciendis et ipsa repudiandae sit similique. A."
}




